package org.dice_research.spab.candidates.five;

import java.util.List;

/**
 * Query ::= Prologue ( SelectQuery | ConstructQuery | DescribeQuery | AskQuery
 * ) ValuesClause
 * 
 * Generated by Root.
 * 
 * Prologue is not implemented, as PREFIXes are removed.
 * 
 * @see https://www.w3.org/TR/sparql11-query/#rQuery
 * 
 * @author Adrian Wilke
 */
public class Query extends Expression {

	public Query() {
		super();
	}

	public Query(Expression parent) {
		super(parent);
	}

	@Override
	protected Expression getNewInstance(Expression parent) {
		return new Query(parent);
	}

	@Override
	protected void addChildren(List<Expression> children) {
		new SelectQuery().addChildren(children);
	}

	@Override
	protected void addRegex(StringBuilder stringBuilder) {
	}
}