package org.dice_research.spab.candidates.five;

import java.util.List;

/**
 * TriplesBlock ::= TriplesSameSubjectPath ( '.' TriplesBlock? )?
 * 
 * Generated by GroupGraphPatternSub.
 * 
 * @see https://www.w3.org/TR/sparql11-query/#rTriplesBlock
 * 
 * @author Adrian Wilke
 */
public class TriplesBlock extends Expression {

	// TODO: Generate based on input queries
	protected final static int MAX_TRIPLES = 3;
	protected int counter;

	public TriplesBlock() {
		super();
		counter = 1;
		sequence.add(new SimpleTriple());
	}

	public TriplesBlock(Expression parent) {
		super(parent);
		counter = ((TriplesBlock) parent).counter + 1;
	}

	@Override
	protected Expression getNewInstance(Expression parent) {
		return new TriplesBlock(parent);
	}

	@Override
	protected void addChildren(List<Expression> children) {

		if (counter < MAX_TRIPLES) {
			TriplesBlock triplesBlock = new TriplesBlock(this);
			SimpleTriple simpleTriple = new SimpleTriple();
			simpleTriple.appendDivider = true;
			triplesBlock.sequence.add(simpleTriple);
			children.add(triplesBlock);
		}

		addRefinedSequenceTo(children);
	}

	@Override
	protected void addRegex(StringBuilder stringBuilder) {
		stringBuilder.append(" ");
		addSequenceToRegex(stringBuilder);
		stringBuilder.append(" ");
	}
}