package org.dice_research.spab.candidates.five;

import java.util.List;

/**
 * WhereClause ::= 'WHERE'? GroupGraphPattern
 * 
 * Only one instance, created by every constructor.
 * 
 * Implemented only with 'WHERE', as this is default Jena representation.
 * 
 * Generated by SelectQuery.
 * 
 * @see https://www.w3.org/TR/sparql11-query/#rWhereClause
 * 
 * @author Adrian Wilke
 */
public class WhereClause extends Expression {

	public WhereClause() {
		super();
		create();
	}

	public WhereClause(WhereClause parent) {
		super(parent);
		create();
	}

	public WhereClause(Expression parent) {
		super(parent);
		create();
	}

	@Override
	protected Expression getNewInstance(Expression parent) {
		return new WhereClause(parent);
	}

	@Override
	protected void addChildren(List<Expression> children) {
		addRefinedSequenceTo(children);
	}

	@Override
	protected void addRegex(StringBuilder stringBuilder) {
		stringBuilder.append("WHERE ");
		addSequenceToRegex(stringBuilder);
	}

	protected void create() {
		if (sequence.isEmpty()) {
			sequence.add(new GroupGraphPattern());
		}
	}
}