package org.dice_research.spab.candidates.six;

/**
 * AskQuery ::= 'ASK' DatasetClause* WhereClause SolutionModifier
 * 
 * Generated by {@link Query}.
 * 
 * @see https://www.w3.org/TR/sparql11-query/#rAskQuery
 * 
 * @author Adrian Wilke
 */
public class AskQuery extends Expression {

	public AskQuery() {
		super();
		sequence.add(new WhereClause());
		sequence.add(new SolutionModifier());
	}

	public AskQuery(Expression origin) {
		super(origin);
	}

	@Override
	protected Expression createInstance(Expression origin) {
		return new AskQuery(origin);
	}

	@Override
	protected void addRegex(StringBuilder stringBuilder) {
		stringBuilder.append("ASK ");
		addWildcard(stringBuilder);
		addSequenceToRegex(stringBuilder);
	}
}