package org.dice_research.spab.candidates.six;

import java.util.LinkedList;
import java.util.List;

/**
 * BuiltInCall ::= Aggregate | 'STR' '(' Expression ')' | 'LANG' '(' Expression
 * ')' | 'LANGMATCHES' '(' Expression ',' Expression ')' | 'DATATYPE' '('
 * Expression ')' | 'BOUND' '(' Var ')' | 'IRI' '(' Expression ')' | 'URI' '('
 * Expression ')' | 'BNODE' ( '(' Expression ')' | NIL ) | 'RAND' NIL | 'ABS'
 * '(' Expression ')' | 'CEIL' '(' Expression ')' | 'FLOOR' '(' Expression ')' |
 * 'ROUND' '(' Expression ')' | 'CONCAT' ExpressionList | SubstringExpression |
 * 'STRLEN' '(' Expression ')' | StrReplaceExpression | 'UCASE' '(' Expression
 * ')' | 'LCASE' '(' Expression ')' | 'ENCODE_FOR_URI' '(' Expression ')' |
 * 'CONTAINS' '(' Expression ',' Expression ')' | 'STRSTARTS' '(' Expression ','
 * Expression ')' | 'STRENDS' '(' Expression ',' Expression ')' | 'STRBEFORE'
 * '(' Expression ',' Expression ')' | 'STRAFTER' '(' Expression ',' Expression
 * ')' | 'YEAR' '(' Expression ')' | 'MONTH' '(' Expression ')' | 'DAY' '('
 * Expression ')' | 'HOURS' '(' Expression ')' | 'MINUTES' '(' Expression ')' |
 * 'SECONDS' '(' Expression ')' | 'TIMEZONE' '(' Expression ')' | 'TZ' '('
 * Expression ')' | 'NOW' NIL | 'UUID' NIL | 'STRUUID' NIL | 'MD5' '('
 * Expression ')' | 'SHA1' '(' Expression ')' | 'SHA256' '(' Expression ')' |
 * 'SHA384' '(' Expression ')' | 'SHA512' '(' Expression ')' | 'COALESCE'
 * ExpressionList | 'IF' '(' Expression ',' Expression ',' Expression ')' |
 * 'STRLANG' '(' Expression ',' Expression ')' | 'STRDT' '(' Expression ','
 * Expression ')' | 'sameTerm' '(' Expression ',' Expression ')' | 'isIRI' '('
 * Expression ')' | 'isURI' '(' Expression ')' | 'isBLANK' '(' Expression ')' |
 * 'isLITERAL' '(' Expression ')' | 'isNUMERIC' '(' Expression ')' |
 * RegexExpression | ExistsFunc | NotExistsFunc
 * 
 * Generated by {@link Constraint}.
 * 
 * @see https://www.w3.org/TR/sparql11-query/#rBuiltInCall
 * 
 * @author Adrian Wilke
 */
public class BuiltInCall extends Expression {

	protected final static String[] CALLS_SINGLE = { "STR", "LANG", "DATATYPE", "IRI", "URI", "ABS", "CEIL", "FLOOR",
			"ROUND", "STRLEN", "UCASE", "LCASE", "ENCODE_FOR_URI", "YEAR", "MONTH", "DAY", "HOURS", "MINUTES",
			"SECONDS", "TIMEZONE", "TZ", "MD5", "SHA1", "SHA256", "SHA384", "SHA512", "isIRI", "isURI", "isBLANK",
			"isLITERAL", "isNUMERIC" };

	protected final static String[] CALLS_DOUBLE = { "LANGMATCHES", "CONTAINS", "STRSTARTS", "STRENDS", "STRBEFORE",
			"STRAFTER", "STRLANG", "STRDT", "sameTerm" };

	protected final static String[] CALLS_TRIPLE = { "IF" };

	protected final static String[] CALLS_VAR = { "BOUND" };

	protected final static String[] CALLS_SINGLE_NIL = { "BNODE" };

	protected final static String[] CALLS_NIL = { "RAND", "NOW", "UUID", "STRUUID" };

	protected final static String[] CALLS_EXPRESSIONLIST = { "CONCAT", "COALESCEF" };

	protected final static String[] CALLS_EXPRESSIONS = { "SUBSTR", "REPLACE", "REGEX" };

	protected final static String[] CALLS_FUNC = { "EXISTS", "NOT EXISTS" };

	/**
	 * Creates list of call with reserved words.
	 */
	public static List<Expression> getInitialInstances() {
		List<Expression> instances = new LinkedList<Expression>();
		for (String call : CALLS_SINGLE) {
			BuiltInCall builtInCall = new BuiltInCall();
			builtInCall.sequence.add(new ExpressionString(call));
			instances.add(builtInCall);
		}
		for (String call : CALLS_DOUBLE) {
			BuiltInCall builtInCall = new BuiltInCall();
			builtInCall.sequence.add(new ExpressionString(call));
			instances.add(builtInCall);
		}
		for (String call : CALLS_TRIPLE) {
			BuiltInCall builtInCall = new BuiltInCall();
			builtInCall.sequence.add(new ExpressionString(call));
			instances.add(builtInCall);
		}
		for (String call : CALLS_VAR) {
			BuiltInCall builtInCall = new BuiltInCall();
			builtInCall.sequence.add(new ExpressionString(call));
			instances.add(builtInCall);
		}
		for (String call : CALLS_SINGLE_NIL) {
			BuiltInCall builtInCall = new BuiltInCall();
			builtInCall.sequence.add(new ExpressionString(call));
			instances.add(builtInCall);
		}
		for (String call : CALLS_NIL) {
			BuiltInCall builtInCall = new BuiltInCall();
			builtInCall.sequence.add(new ExpressionString(call));
			instances.add(builtInCall);
		}
		for (String call : CALLS_EXPRESSIONLIST) {
			BuiltInCall builtInCall = new BuiltInCall();
			builtInCall.sequence.add(new ExpressionString(call));
			instances.add(builtInCall);
		}
		for (String call : CALLS_EXPRESSIONS) {
			BuiltInCall builtInCall = new BuiltInCall();
			builtInCall.sequence.add(new ExpressionString(call));
			instances.add(builtInCall);
		}
		for (String call : CALLS_FUNC) {
			BuiltInCall builtInCall = new BuiltInCall();
			builtInCall.sequence.add(new ExpressionString(call));
			instances.add(builtInCall);
		}
		return instances;
	}

	public BuiltInCall() {
		super();
	}

	public BuiltInCall(Expression origin) {
		super(origin);
	}

	@Override
	protected Expression createInstance(Expression origin) {
		return new BuiltInCall(origin);
	}

	@Override
	protected void addRegex(StringBuilder stringBuilder) {
		addSequenceToRegex(stringBuilder);
		addWildcard(stringBuilder);
	}
}