package org.dice_research.spab.candidates.six;

/**
 * GroupOrUnionGraphPattern ::= GroupGraphPattern ( 'UNION' GroupGraphPattern )*
 * 
 * Generated by {@link GraphPatternNotTriples}.
 * 
 * @see https://www.w3.org/TR/sparql11-query/#rGroupOrUnionGraphPattern
 * 
 * @author Adrian Wilke
 */
public class GroupOrUnionGraphPattern extends Expression {

	public GroupOrUnionGraphPattern() {
		sequence.add(new GroupGraphPattern());
		sequence.add(new ExpressionString(" UNION "));
		sequence.add(new GroupGraphPattern());
	}

	public GroupOrUnionGraphPattern(Expression origin) {
		super(origin);
	}

	@Override
	protected Expression createInstance(Expression origin) {
		return new GroupOrUnionGraphPattern(origin);
	}

	@Override
	protected void addRegex(StringBuilder stringBuilder) {
		addSequenceToRegex(stringBuilder);
	}
}