package org.dice_research.spab.candidates.six;

/**
 * GroupGraphPattern ::= '{' ( SubSelect | GroupGraphPatternSub ) '}'
 * 
 * Generated by WhereClause. TODO
 * 
 * @see https://www.w3.org/TR/sparql11-query/#rGroupGraphPattern
 * 
 * @author Adrian Wilke
 */
public class GroupGraphPattern extends Expression {

	public GroupGraphPattern() {
		GroupGraphPatternSub groupGraphPatternSub = new GroupGraphPatternSub();
		sequence.add(groupGraphPatternSub);
	}

	public GroupGraphPattern(Expression origin) {
		super(origin);
	}

	@Override
	protected Expression createInstance(Expression origin) {
		return new GroupGraphPattern(origin);
	}

	@Override
	protected void addRegex(StringBuilder stringBuilder) {
		addSequenceToRegex(stringBuilder);
	}
}