package org.dice_research.spab.candidates.six;

/**
 * HavingClause ::= 'HAVING' HavingCondition+
 * 
 * Generated by {@link SolutionModifier}
 * 
 * @see https://www.w3.org/TR/sparql11-query/#rHavingClause
 * 
 * @author Adrian Wilke
 */
public class HavingClause extends Expression {

	public HavingClause() {
		super();
	}

	public HavingClause(Expression origin) {
		super(origin);
	}

	@Override
	protected Expression createInstance(Expression origin) {
		return new HavingClause(origin);
	}

	@Override
	protected void addRegex(StringBuilder stringBuilder) {
		addWildcard(stringBuilder);
		stringBuilder.append("HAVING");
		addWildcard(stringBuilder);
	}
}