package org.dice_research.spab.candidates.six;

/**
 * LimitClause ::= 'LIMIT' INTEGER
 * 
 * Generated by {@link LimitOffsetClauses}
 * 
 * @see https://www.w3.org/TR/sparql11-query/#rLimitClause
 * 
 * @author Adrian Wilke
 */
public class LimitClause extends Expression {

	public LimitClause() {
		super();
	}

	public LimitClause(Expression origin) {
		super(origin);
	}

	@Override
	protected Expression createInstance(Expression origin) {
		return new LimitClause(origin);
	}

	@Override
	protected void addRegex(StringBuilder stringBuilder) {
		addWildcard(stringBuilder);
		stringBuilder.append("LIMIT");
		addWildcard(stringBuilder);
	}
}