package org.dice_research.spab.candidates.six;

/**
 * OffsetClause ::= 'OFFSET' INTEGER
 * 
 * Generated by {@link LimitOffsetClauses};
 * 
 * @see https://www.w3.org/TR/sparql11-query/#rOffsetClause
 * 
 * @author Adrian Wilke
 */
public class OffsetClause extends Expression {

	public OffsetClause() {
		super();
	}

	public OffsetClause(Expression origin) {
		super(origin);
	}

	@Override
	protected Expression createInstance(Expression origin) {
		return new OffsetClause(origin);
	}

	@Override
	protected void addRegex(StringBuilder stringBuilder) {
		addWildcard(stringBuilder);
		stringBuilder.append("OFFSET");
		addWildcard(stringBuilder);
	}
}