package org.dice_research.spab.candidates.six;

/**
 * Query ::= Prologue ( SelectQuery | ConstructQuery | DescribeQuery | AskQuery
 * ) ValuesClause
 * 
 * Generated by {@link Root}.
 * 
 * Prologue is not implemented, as PREFIXes are removed.
 * 
 * @see https://www.w3.org/TR/sparql11-query/#rQuery
 * 
 * @author Adrian Wilke
 */
public class Query extends Expression {

	public Query() {
		SelectQuery selectQuery = new SelectQuery();
		sequence.add(selectQuery);
	}

	public Query(Expression origin) {
		super(origin);
	}

	@Override
	protected Expression createInstance(Expression origin) {
		return new Query(origin);
	}

	@Override
	protected void addRegex(StringBuilder stringBuilder) {
		addSequenceToRegex(stringBuilder);
	}
}