package org.dice_research.spab.candidates.six;

/**
 * SolutionModifier ::= GroupClause? HavingClause? OrderClause?
 * LimitOffsetClauses?
 * 
 * Generated by {@link SelectQuery}
 * 
 * @see https://www.w3.org/TR/sparql11-query/#rSolutionModifier
 * 
 * @author Adrian Wilke
 */
public class SolutionModifier extends Expression {

	public SolutionModifier() {
		GroupClause groupClause = new GroupClause();
		sequence.add(groupClause);
	}

	public SolutionModifier(Expression origin) {
		super(origin);
	}

	@Override
	protected Expression createInstance(Expression origin) {
		return new SolutionModifier(origin);
	}

	@Override
	protected void addRegex(StringBuilder stringBuilder) {
		stringBuilder.append("\\{");
		addSequenceToRegex(stringBuilder);
		stringBuilder.append("\\}");
	}
}