package org.dice_research.spab.candidates.six;

import java.util.List;

import org.dice_research.spab.input.Input;

/**
 * TriplesBlock ::= TriplesSameSubjectPath ( '.' TriplesBlock? )?
 * 
 * Generated by {@link GroupGraphPatternSub}.
 * 
 * Contains several {@link TriplesBlock} and {@link Triple}.
 * 
 * @see https://www.w3.org/TR/sparql11-query/#rTriplesBlock
 * 
 * @author Adrian Wilke
 */
public class TriplesBlock extends Expression {

	// TODO Set length based on input
	protected final static int MAX_TRIPLE_BLOCKS = 3;
	
	// TODO Could be set in another way.
	public boolean createTripleBlock = false;
	protected int tripleBlockCreationCount;

	/**
	 * Creates triple block containing one triple.
	 */
	public TriplesBlock() {
		sequence.add(new Triple());
		tripleBlockCreationCount = MAX_TRIPLE_BLOCKS;
	}

	/**
	 * Used for recursive refinement. Will not create additional triple blocks to
	 * this sequence by default.
	 */
	public TriplesBlock(Expression origin) {
		super(origin);
	}

	@Override
	protected Expression createInstance(Expression origin) {
		return new TriplesBlock(origin);
	}

	@Override
	protected void addRegex(StringBuilder stringBuilder) {
		addSequenceToRegex(stringBuilder, " \\. ");
	}

	@Override
	public List<Expression> getRefinements(Input input) {
		List<Expression> refinements = getRefinementsOfSequence(input);

		if (createTripleBlock && tripleBlockCreationCount > 1) {
			TriplesBlock triplesBlock = new TriplesBlock();
			triplesBlock.tripleBlockCreationCount = tripleBlockCreationCount - 1;
			triplesBlock.createTripleBlock = true;

			Expression additionalBlock = createInstance(this);
			additionalBlock.sequence.add(triplesBlock);
			refinements.add(additionalBlock);
			createTripleBlock = false;
		}

		return refinements;
	}

}