package org.dice_research.spab.candidates.six;

/**
 * WhereClause ::= 'WHERE'? GroupGraphPattern
 * 
 * Only one instance, created by every constructor.
 * 
 * Implemented only with 'WHERE', as this is default Jena representation.
 * 
 * Generated by {@link SelectQuery}.
 * 
 * @see https://www.w3.org/TR/sparql11-query/#rWhereClause
 * 
 * @author Adrian Wilke
 */
public class WhereClause extends Expression {

	public WhereClause() {
		GroupGraphPattern groupGraphPattern = new GroupGraphPattern();
		sequence.add(groupGraphPattern);
	}

	public WhereClause(Expression origin) {
		super(origin);
	}

	@Override
	protected Expression createInstance(Expression origin) {
		return new WhereClause(origin);
	}

	@Override
	protected void addRegex(StringBuilder stringBuilder) {
		stringBuilder.append("WHERE ");
		addSequenceToRegex(stringBuilder);
	}
}